### ISSUE TITLE
User preference for ignored syntax types?

### ISSUE THREAD

**Issue by JerseyMilker** [bluegray/Highlighter#11]
I wouldn't mind being about to disable highlighting for specific syntax modes, like plain text, etc.  Maybe we could have "highlighter_ignore_syntax_modes" array in it's user prefs JSON?

For example... This would especially be helpful because Highlighter highlights all the mixed whitespace used intentionally by packages like [SublimeGit](https://sublime.wbond.net/packages/SublimeGit) package (SublimeGit needs to use mixed whitespace in git diff output, but it uses it's own syntax mode, so above suggestion would allow us to disable Highlighter for clashing syntax modes).

PS. It's a great package though, thank you for Highlighter!

**Comment by bluegray** [comment]
Adding support via #15
