### ISSUE TITLE
Add Command Palette commands for enable/disable?

### ISSUE THREAD

**Issue by JesseLeite** [bluegray/Highlighter#13]
Add Command Palette commands...
`Highlighter: Disable Highlighting`
`Highlighter: Enable Highlighting`

Or maybe just...
`Highlighter: Toggle Highlighting`

...I know I can do this through Highlighter's settings file.  Would be nice to be able to quickly toggle with Command Palette IMO though :)

**Comment by bluegray** [comment]
Added a toggle command in 0c0cb8a :)

**Comment by JesseLeite** [comment]
Oh nice thanks!
