### ISSUE TITLE
Add «insecable» space by default

### ISSUE THREAD

**Issue by 4sStylZ** [bluegray/Highlighter#18]
Hi,

The insecable space is used in France « ». It can cause many issues in a php code or in a sql code.
I have used this regex but sometime the highlighter don’t match my special character : 
```(` +\t+)|[\u2018\u201c\u201d\u2013\u2014]|[\t ]+$```

Any suggestion?

**Comment by bluegray** [comment]
I added the [non breaking space](https://en.wikipedia.org/wiki/Non-breaking_space), to the list of unicode characters to highlight: 4f50198
