### ISSUE TITLE
Highlighter doesn't start automaticaly

### ISSUE THREAD

**Issue by MichalTaratuta** [bluegray/Highlighter#22]
even though I have the `"highlighter_enabled": true`  the highlight doesn't work until I'll toggle from `on -> off -> on`

I would expect the highlighter always work in the backgroud.

**Comment by jdgregson** [comment]
Yes, I have to turn it off and on again for every single file. This is proving rather useless.

**Comment by jdgregson** [comment]
Trailing Spaces, the package that this was originally pulled from, is able to highlight in all files automatically. Maybe someone can locate the differences and get this one working again? Until then, I have little reason to keep this thing around.

**Comment by gravityfire-tw** [comment]
> even though I have the `"highlighter_enabled": true` the highlight doesn't work until I'll toggle from `on -> off -> on`
> 
> I would expect the highlighter always work in the backgroud
the same problem,
I have to enable for each file... QQ
